// <auto-generated />
using System;
using CMS.Modules.Voices.Infrastructure.Persistence;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace CMS.Modules.Voices.Infrastructure.Persistence.Migrations;

[DbContext(typeof(VoicesDbContext))]
partial class VoicesDbContextModelSnapshot : ModelSnapshot
{
    protected override void BuildModel(ModelBuilder modelBuilder)
    {
#pragma warning disable 612, 618
        modelBuilder
            .HasDefaultSchema("voices")
            .HasAnnotation("ProductVersion", "10.0.10")
            .HasAnnotation("Relational:MaxIdentifierLength", 63);

        NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

        modelBuilder.Entity("CMS.Modules.Voices.Domain.Entities.VoiceItem", b =>
            {
                b.Property<Guid>("Id")
                    .HasColumnType("uuid");

                b.Property<string>("AudioUrl")
                    .IsRequired()
                    .HasMaxLength(1000)
                    .HasColumnType("character varying(1000)");

                b.Property<DateTime>("CreatedAtUtc")
                    .HasColumnType("timestamp with time zone");

                b.Property<string>("CustomerName")
                    .IsRequired()
                    .HasMaxLength(200)
                    .HasColumnType("character varying(200)");

                b.Property<string>("Description")
                    .HasMaxLength(2000)
                    .HasColumnType("character varying(2000)");

                b.Property<bool>("IsPublished")
                    .HasColumnType("boolean");

                b.Property<DateTime?>("PublishedAtUtc")
                    .HasColumnType("timestamp with time zone");

                b.Property<int>("SortOrder")
                    .HasColumnType("integer");

                b.Property<string>("Subtitle")
                    .HasMaxLength(300)
                    .HasColumnType("character varying(300)");

                b.Property<DateTime?>("UpdatedAtUtc")
                    .HasColumnType("timestamp with time zone");

                b.HasKey("Id");

                b.HasIndex("IsPublished", "SortOrder");

                b.ToTable("VoiceItems", "voices");
            });
#pragma warning restore 612, 618
    }
}
