<Project Sdk="Microsoft.NET.Sdk.Razor">

  <PropertyGroup>
    <TargetFramework>net10.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
    <AddRazorSupportForMvc>true</AddRazorSupportForMvc>
  </PropertyGroup>

  <ItemGroup>
    <FrameworkReference Include="Microsoft.AspNetCore.App" />
    <PackageReference Include="Microsoft.FeatureManagement.AspNetCore" Version="4.6.0" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\Application\CMS.Modules.News.Application.csproj" />
    <ProjectReference Include="..\..\Seo\Web\CMS.Modules.Seo.Web.csproj" />
    <ProjectReference Include="..\..\Seo\Application\CMS.Modules.Seo.Application.csproj" />
  </ItemGroup>

</Project>
