// <auto-generated />
using System;
using CMS.Modules.Shop.Infrastructure.Persistence;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace CMS.Modules.Shop.Infrastructure.Persistence.Migrations
{
    [DbContext(typeof(ShopDbContext))]
    [Migration("20260803170000_InitialShop")]
    partial class InitialShop
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasDefaultSchema("shop")
                .HasAnnotation("ProductVersion", "10.0.10")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("CMS.Modules.Shop.Domain.Entities.Product", b =>
                {
                    b.Property<Guid>("Id").ValueGeneratedOnAdd().HasColumnType("uuid");
                    b.Property<Guid?>("CategoryId").HasColumnType("uuid");
                    b.Property<string>("CoverImageUrl").HasMaxLength(1000).HasColumnType("character varying(1000)");
                    b.Property<DateTime>("CreatedAtUtc").HasColumnType("timestamp with time zone");
                    b.Property<string>("Currency").IsRequired().HasMaxLength(8).HasColumnType("character varying(8)");
                    b.Property<string>("Description").IsRequired().HasColumnType("text");
                    b.Property<bool>("IsAvailable").HasColumnType("boolean");
                    b.Property<decimal>("Price").HasPrecision(18, 2).HasColumnType("numeric(18,2)");
                    b.Property<DateTime?>("PublishedAtUtc").HasColumnType("timestamp with time zone");
                    b.Property<string>("Slug").IsRequired().HasMaxLength(300).HasColumnType("character varying(300)");
                    b.Property<string>("Status").IsRequired().HasMaxLength(32).HasColumnType("character varying(32)");
                    b.Property<string>("Title").IsRequired().HasMaxLength(300).HasColumnType("character varying(300)");
                    b.Property<DateTime?>("UpdatedAtUtc").HasColumnType("timestamp with time zone");
                    b.HasKey("Id");
                    b.HasIndex("CategoryId");
                    b.HasIndex("Slug").IsUnique();
                    b.ToTable("Products", "shop");
                });

            modelBuilder.Entity("CMS.Modules.Shop.Domain.Entities.ShopCategory", b =>
                {
                    b.Property<Guid>("Id").ValueGeneratedOnAdd().HasColumnType("uuid");
                    b.Property<DateTime>("CreatedAtUtc").HasColumnType("timestamp with time zone");
                    b.Property<string>("Description").HasMaxLength(4000).HasColumnType("character varying(4000)");
                    b.Property<string>("ImageUrl").HasMaxLength(1000).HasColumnType("character varying(1000)");
                    b.Property<string>("Name").IsRequired().HasMaxLength(200).HasColumnType("character varying(200)");
                    b.Property<string>("Slug").IsRequired().HasMaxLength(200).HasColumnType("character varying(200)");
                    b.Property<int>("SortOrder").HasColumnType("integer");
                    b.Property<DateTime?>("UpdatedAtUtc").HasColumnType("timestamp with time zone");
                    b.HasKey("Id");
                    b.HasIndex("Slug").IsUnique();
                    b.ToTable("Categories", "shop");
                });

            modelBuilder.Entity("CMS.Modules.Shop.Domain.Entities.ShopSettings", b =>
                {
                    b.Property<Guid>("Id").ValueGeneratedOnAdd().HasColumnType("uuid");
                    b.Property<DateTime>("CreatedAtUtc").HasColumnType("timestamp with time zone");
                    b.Property<string>("Mode").IsRequired().HasMaxLength(32).HasColumnType("character varying(32)");
                    b.Property<DateTime?>("UpdatedAtUtc").HasColumnType("timestamp with time zone");
                    b.HasKey("Id");
                    b.ToTable("Settings", "shop");
                });

            modelBuilder.Entity("CMS.Modules.Shop.Domain.Entities.Product", b =>
                {
                    b.HasOne("CMS.Modules.Shop.Domain.Entities.ShopCategory", "Category")
                        .WithMany("Products")
                        .HasForeignKey("CategoryId")
                        .OnDelete(DeleteBehavior.SetNull);
                    b.Navigation("Category");
                });

            modelBuilder.Entity("CMS.Modules.Shop.Domain.Entities.ShopCategory", b =>
                {
                    b.Navigation("Products");
                });
#pragma warning restore 612, 618
        }
    }
}

