using CMS.Modules.Shop.Domain.Enums;

namespace CMS.Modules.Shop.Application.Products;

public sealed record ProductListItemDto(
    Guid Id,
    string Title,
    string Slug,
    decimal Price,
    string Currency,
    bool IsAvailable,
    bool IsPurchasable,
    ProductStatus Status,
    ProductType ProductType,
    string? CategoryName,
    string? BrandName,
    string? CoverImageUrl,
    int VariationCount,
    int SpecificationCount,
    int? StockQuantity,
    bool UnlimitedStock,
    bool HasUnlimitedVariation,
    int VariationStockTotal,
    DateTime CreatedAtUtc);

public sealed record ProductImageDto(Guid Id, string Url, string? AltText, int SortOrder, bool IsMain);

public sealed record ProductSpecificationDto(Guid Id, string Key, string Value, int SortOrder);

public sealed record SaveProductSpecificationCommand(string Key, string Value, int SortOrder);

public sealed record ProductVariationDto(
    Guid Id,
    string Sku,
    string? AttributeSummary,
    decimal Price,
    decimal? SalePrice,
    int? StockQuantity,
    bool UnlimitedStock,
    string? ImageUrl,
    decimal? Weight,
    VariationStatus Status);

public sealed record ProductDetailDto(
    Guid Id,
    string Title,
    string Slug,
    string ShortDescription,
    string Description,
    decimal Price,
    decimal? SalePrice,
    DateTime? SaleStartsAtUtc,
    DateTime? SaleEndsAtUtc,
    string Currency,
    bool IsAvailable,
    bool IsPurchasable,
    ProductStatus Status,
    ProductType ProductType,
    Guid? CategoryId,
    Guid? BrandId,
    string? CoverImageUrl,
    string? VideoUrl,
    int? StockQuantity,
    bool UnlimitedStock,
    int LowStockThreshold,
    decimal? Weight,
    int MinimumOrderQuantity,
    int? WholesaleMinimumOrderQuantity,
    decimal? WholesaleMinimumOrderAmount,
    string? Sku,
    string? MetaTitle,
    string? MetaDescription,
    string? SeoKeywords,
    string? CanonicalUrl,
    string? OgTitle,
    string? OgDescription,
    string? OgImageUrl,
    string? FaqJson,
    IReadOnlyList<ProductImageDto> Images,
    IReadOnlyList<ProductVariationDto> Variations,
    IReadOnlyList<ProductSpecificationDto> Specifications);

public sealed record SaveProductVariationCommand(
    Guid? Id,
    string Sku,
    string? AttributeSummary,
    decimal Price,
    decimal? SalePrice,
    int? StockQuantity,
    bool UnlimitedStock,
    string? ImageUrl,
    decimal? Weight,
    VariationStatus Status);

public sealed record SaveProductImageCommand(string Url, string? AltText, int SortOrder, bool IsMain);

public sealed record SaveProductCommand(
    string Title,
    string? Slug,
    string? ShortDescription,
    string? Description,
    decimal Price,
    decimal? SalePrice,
    DateTime? SaleStartsAtUtc,
    DateTime? SaleEndsAtUtc,
    string? Currency,
    bool IsAvailable,
    bool IsPurchasable,
    ProductStatus Status,
    Guid? CategoryId,
    Guid? BrandId,
    string? CoverImageUrl,
    string? VideoUrl,
    int? StockQuantity,
    bool UnlimitedStock,
    int LowStockThreshold,
    decimal? Weight,
    int MinimumOrderQuantity,
    int? WholesaleMinimumOrderQuantity,
    decimal? WholesaleMinimumOrderAmount,
    string? Sku,
    string? MetaTitle,
    string? MetaDescription,
    string? SeoKeywords,
    string? CanonicalUrl,
    string? OgTitle,
    string? OgDescription,
    string? OgImageUrl,
    string? FaqJson,
    IReadOnlyList<SaveProductImageCommand>? Images,
    IReadOnlyList<SaveProductVariationCommand>? Variations);

public sealed record PublicProductListItemDto(
    Guid Id,
    string Title,
    string Slug,
    string? Excerpt,
    decimal Price,
    decimal? DisplayPrice,
    string Currency,
    bool IsAvailable,
    bool CanPurchase,
    bool ShowPrice,
    string? CategoryName,
    string? BrandName,
    string? CoverImageUrl,
    double? AverageRating,
    int ReviewCount);

public sealed record PublicVariationDto(
    Guid Id,
    string Sku,
    string? AttributeSummary,
    decimal Price,
    decimal DisplayPrice,
    int? StockQuantity,
    bool UnlimitedStock,
    string? ImageUrl,
    VariationStatus Status);

public sealed record PublicReviewDto(
    Guid Id,
    string AuthorName,
    int Rating,
    string Comment,
    string? AdminResponse,
    DateTime CreatedAtUtc);

public sealed record PublicProductDetailDto(
    Guid Id,
    string Title,
    string Slug,
    string ShortDescription,
    string Description,
    decimal Price,
    decimal DisplayPrice,
    string Currency,
    bool IsAvailable,
    bool CanPurchase,
    bool ShowPrice,
    ProductType ProductType,
    string? CategoryName,
    string? BrandName,
    string? CoverImageUrl,
    string? VideoUrl,
    int MinimumOrderQuantity,
    int? StockQuantity,
    bool UnlimitedStock,
    string? MetaTitle,
    string? MetaDescription,
    string? SeoKeywords,
    string? CanonicalUrl,
    string? OgTitle,
    string? OgDescription,
    string? OgImageUrl,
    string? FaqJson,
    IReadOnlyList<ProductImageDto> Images,
    IReadOnlyList<PublicVariationDto> Variations,
    IReadOnlyList<PublicReviewDto> Reviews,
    double? AverageRating,
    int ReviewCount);
